ALTER TABLE usuarios ADD ativo BOOLEAN NOT NULL;

ALTER TABLE listas ADD ativo BOOLEAN NOT NULL;

ALTER TABLE tipos ADD ativo BOOLEAN NOT NULL;

ALTER TABLE apiconsumida ADD ativo BOOLEAN NOT NULL;

ALTER TABLE pais ADD ativo BOOLEAN NOT NULL;

ALTER TABLE status ADD ativo BOOLEAN NOT NULL;

ALTER TABLE registros ADD ativo BOOLEAN NOT NULL;

